codecov:
  require_ci_to_pass: yes
  token: 8782d1e7-ffa7-4d2b-81d1-1e936bd8a490

coverage: 
  precision: 2 
  round: down
  range: "70...100"

comment: 
  layout: "reach, diff, flags, files, footer" 
  behavior: default
  require_changes: no

# when modifying this file, validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate