// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqOpSrup7y-JpPs0j-dsKLehCjcHXu1Y',
    appId: '1:1061339962450:web:408029267dbf1b14f3538b',
    messagingSenderId: '1061339962450',
    projectId: 'harvest-application-6a156',
    authDomain: 'harvest-application-6a156.firebaseapp.com',
    storageBucket: 'harvest-application-6a156.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzshOH_NCmR3uu7d99luFW9lBQSL_o8HI',
    appId: '1:1061339962450:android:6f4e306d33fc6764f3538b',
    messagingSenderId: '1061339962450',
    projectId: 'harvest-application-6a156',
    storageBucket: 'harvest-application-6a156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9aPjrZlGVBhNrA62ptbunMfrwnnaCEgE',
    appId: '1:1061339962450:ios:341945bd8a3d9e7cf3538b',
    messagingSenderId: '1061339962450',
    projectId: 'harvest-application-6a156',
    storageBucket: 'harvest-application-6a156.appspot.com',
    iosBundleId: 'com.example.harvestApplicationNoPhp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9aPjrZlGVBhNrA62ptbunMfrwnnaCEgE',
    appId: '1:1061339962450:ios:341945bd8a3d9e7cf3538b',
    messagingSenderId: '1061339962450',
    projectId: 'harvest-application-6a156',
    storageBucket: 'harvest-application-6a156.appspot.com',
    iosBundleId: 'com.example.harvestApplicationNoPhp',
  );
}
